### ISSUE TITLE
Add Feature Request Template

### ISSUE THREAD

**Issue by 0x4D5352** [0x4D5352/.github#2]
Create a template file that can be used for `.github` folders in other repositories.

Example feature request report from [FreeCodeCamp](https://www.freecodecamp.org/news/how-to-use-the-dot-github-repository/):

```yaml
name: ✨Feature Request
description: Request a new feature or enhancement
labels: ["enhancement"]
title: "[FEAT]: "
body:
  - type: markdown
    attributes:
      value: |
        Please make sure this feature request hasn't been already submitted by someone by looking through other open/closed issues
  
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Give us a brief description of the feature or enhancement you would like
    validations:
      required: true
      
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Give us some additional information on the feature request like proposed solutions, links, screenshots, etc.
```
